### ISSUE TITLE
Joining output back to footprints

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/buildings#32]
I've been able to replicate the running of this code on a separate machine (PR coming soon). This repo, so far, seems to output data (features) to JSON files in the `data/json` directory. The JSON files seem limited to only features for the buildings, but does not contain the footprint information (which are located in `byTract/buildings/` directory).

Of course, to map it, the footprints are needed. However, I did not see an obvious key to match the data JSON files back to the GeoJSON files. I assume the file names, e.g., `data/json/1001.json` and `byTract/buildings/1001.geojson`, are related.

Is there a good primary key to merge data back to the footprints? Or, is there another suggested route?

**Comment by nicklucius** [comment]
Thanks for your feedback, @tomschenkjr! There are a few other items in the workflow that are not clear in the documentation, which I am excited to fix so that this becomes more usable.

Here are the high-level manual steps in the complete workflow:

1. Geocode an incoming dataset (such as 311 calls), and convert it to a Spatial Data Frame. 
2. Use this repo's `writeTracts` function to create the files in `data/json`, which separates the data by Census Tract.
3. Use this repo's `buildJSON` function, which iterates through once Census Tract at a time, to assign each of the income dataset's rows to a `bldg_id` or a `PIN`.
4. Use the `bldg_id` or `PIN` to link each row to a footprint. That is what `combine-json.R` does.

A few important notes:

- With some of the different data model prototypes we've had (1 large JSON file with nesting, etc.), we have some new code that hasn't been pushed yet. I am looking forward to pushing it out here.
- Some of the code in this repo will be deprecated due to the experimental nature of this project. However, anything that's already been turned into a function is least likely to be changing.
- PRs would be awesome!

**Comment by tomschenkjr** [comment]
Got it, I was missing the `combine-json.R` role.
